### PR TITLE
Add HERMES Core Project

### PR DESCRIPTION
**Pull request by Alrobbertz**

### CODE REVIEW

**Comment by Alrobbertz** [comment]
@ehsteve @dbarrous Do you want to look this over when you get a chance?

**Comment by sapols** [comment]
Hi, sorry for the super slow response. I've got a backlog of other tasks before I can start this review, and with holidays/conferences it might be a while.

**Comment by Alrobbertz** [comment]
> Hi, sorry for the super slow response. I've got a backlog of other tasks before I can start this review, and with holidays/conferences it might be a while.

No worries! We're also slow on our end getting internal review and thinking what other packages we might want to add. No rush to get review while it's a draft stage here.

**Comment by sapols** [comment]
What do you expect is your timeline for getting this PR out of draft and ready for review?

**Comment by Alrobbertz** [comment]
> What do you expect is your timeline for getting this PR out of draft and ready for review?

We may want to add more of the HERMES Mission Packages (from our [org](https://github.com/HERMES-SOC)) or from the SpaceWeather SOC ([org](https://github.com/swxsoc)) in the future. But for now I'll open this one and we can use this as a learning experience for other packages we might want to add.

**Review by sapols — APPROVED** [review]

**Comment by sapols** [comment]
I approved this PR because I agree with your self evaluation and I'm ready to merge this in. Welcome HERMES Core to PyHC!

It was actually an easy decision. Your repo is one of the more professional and well-fleshed-out repos we have. I appreciate that you added "hermes" to the taxonomy too. A lot of people forget about the taxonomy. So maybe this wasn't too crazy of a "learning experience" but hopefully you won't mind.

The only thing I fixed was your whitespace alignment. Not a big deal, just watch for that next time.

**Comment by sapols** [comment]
Whoops, one thing I overlooked: your logo link should've been a direct link to the raw image (in your case, https://raw.githubusercontent.com/HERMES-SOC/hermes_core/main/docs/logo/hermes_logo.png). That link is used to render the "card" view in the PyHC projects page, which almost no one looks at, so not a huge deal. We haven't documented this either, so no way you could've known.

I'll update the documentation. I should probably also audit these projects soon because you're not the only group to use a non-raw GitHub URL.

**Pull request merged**
