### PR TITLE
Requesting addition of pySPEDAS to the PyHC Core Packages

### PR DESCRIPTION
**Pull request by jibarnum**
As mentioned at the PyHC Fall 2021 Meeting, there's interest in having pySPEDAS be included as part of the PyHC Core Packages. Officially putting this idea forward here.

### CODE REVIEW

**Comment by sapols** [comment]
I'm all for this. Just for the sake of transparency though I'll say my one concern is that how tightly coupled pySPEDAS is with PyTplot has caused problems for people lately. PyTplot has a QT dependency in particular that keeps breaking on import. I dealt with it in Deepnote, Alec and co saw it in their environment, and it's the main thing that broke our Gallery's CI build. Eric G is making a new version of PyTplot that uses matplotlib on the backend instead of QT and it might make sense to wait for that until we merge this. Only issue there is he still has to talk to Bryan and the rest of the community about whether the matplotlib version should become the main PyTplot package or if it'll be an alternative that lives next to it.

**Comment by jibarnum** [comment]
Hello @heliophysicsPy/core-packages ! Just wanted to get your thoughts looped in here.

@sapols looks like a discussion has been started that addresses your concerns [here](https://github.com/MAVENSDC/PyTplot/issues/159#issuecomment-969168468) (I notice you've already commented as well!).

**Review by namurphy — APPROVED** [review]
Adding pySPEDAS to the list of core packages seems like a good idea to me.  I'm for this change.

**Comment by jibarnum** [comment]
There's general agreement it sounds like from here (and from past conversations). Officially adding pySPEDAS as a new PyHC core package!

**Pull request merged**
