### PR TITLE
Add SkyWinder to PyHC project list

### PR DESCRIPTION
**Pull request by ckjellstrand**
SkyWinder is an open-source Python package useful for instrument control, telemetry, and image analysis. It is adapted from software that successfully managed flight control, telemetry, preliminary image analysis, and data visualization for a balloon-borne mission and it has broad uses for mid- and upper-atmosphere science instrumentation including aurora, cloud, and airglow imagers.
 
This software consists of two distinct parts: the flight and analysis modules. The SkyWinder flight package includes modular distributed flight control including telemetry and subsystem coordination for running mobile aeronomy experiments such as balloon-borne payloads, airplanes, sounding rockets, and suborbital reusable launch vehicles (sRLVs), as well as isolated semi-autonomous ground instruments. The SkyWinder analysis software provides functionality more broadly useful in neutral upper atmosphere dynamics, such as pointing reconstruction, image projection, preliminary image processing, and various image analysis techniques.
 
The main “SkyWinder” package is the more mature of the two packages and currently meets most of the PyHC standards. It still requires implementation of test coverage, implementation of PEP8 evaluation, widespread docstring additions, and contributor guidelines. These measures will be straightforward to implement: the package already includes automated unit tests, flake8 evaluation, and a paper has been submitted documenting the package which will be adapted to embedded docstrings.
 
The “SkyWinder-Analysis” package is less mature and requires more work to meet the PyHC standards. It does not yet have testing or documentation in place, and we are holding off automating the PyPi packaging until the code is more developed. Our hope is that the “app” structure we use will make this code easy to understand without the need for long documentation. We also need to host many of the resources used by this analysis code on the same website (NASA’s Space Flight Data Facility) as the raw data. Our efforts are focused on bringing this code up to the PyHC standards.

### CODE REVIEW

**Comment by sapols** [comment]
Thanks for this PR! I definitely agree we should add SkyWinder to PyHC. Just a few quick things I want to address first:

- The keywords should come from our [taxonomy](https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/main/_data/taxonomy.yml). There are 7 categories of keywords; please include any and all keywords that pertain to your packages. The more the merrier. But please only use keywords from the taxonomy and please spell them exactly as they appear in the taxonomy file.
- For fields you don't use (e.g. `url`) please just omit the field rather than give it an empty string value.
- It's okay that some PyHC standards aren't met yet as long as you're working toward them.
- Not a requirement but just a suggestion: if you expect "SkyWinder-Analysis" to have any users, we do encourage you to go ahead and publish to PyPI. Even if the code is underdeveloped, minor version numbers like 0.0.1, 0.0.2, etc. can be used.

**Comment by sapols** [comment]
@ckjellstrand pinging you to make sure you saw my comment.

**Comment by sapols** [comment]
@ckjellstrand ? This PR has been stale almost a month.

**Comment by ckjellstrand** [comment]
Hello,

I apologize for the delay. I have updated the keywords to match the
established taxonomy, removed the fields that had a blank string, and added
SkyWinder-Analysis to PyPi. Do I need to create a new pull request? The
current one seems to have updated automatically.

Thank you,
Bjorn

**Comment by sapols** [comment]
No new PR needed, this looks great. I'll go ahead and merge. Welcome to PyHC.

**Pull request merged**
