### PR TITLE
Cleanup and bump to Boostrap v4

### LINKED ISSUE #12: Highlighting of navbar pills broken
In the menu at the top right of the page, presumably the page you're on should be highlighted, e.g. when I'm on the "Meetings" page, "Meetings" in the menu should be highlighted in blue.

However, the "Home" item is highlighted regardless of what page you navigate to.

### PR DESCRIPTION
**Pull request by wtbarnes**
Closes #12, #17, #19, #21

### CODE REVIEW

**Comment by wtbarnes** [comment]
Take a look at the deploy preview and let me know what you think. I can also implement #20 if you think that is a good idea as well.

**Comment by ehsteve** [comment]
@wtbarnes This is much nicer! Do you want to go ahead and move the people onto a new page? Also should we consider removing the blog component? We haven't used it and it doesn't look great. Is there any way to make it easier to see the deployed branch? I had to click through to find it and it says above this "This branch has not been deployed" which is confusing.

**Comment by ehsteve** [comment]
ping @alex-aquila

**Comment by ehsteve** [comment]
Also how about we replace the default image with the following 
640px-ibexheliosphererevised. The image I found for here is overly complicated. I know there was talk of coming up with a logo but not sure how long that will take. This image is currently being used on GitHub as well as the icon for the riot room.

**Comment by wtbarnes** [comment]
@ehsteve Sure I can move the people to a new page. Should we have a separate page for projects as well? Maybe then we can move the "About" to the home page.

I agree that the blog is a bit unnecessary at this point. Rather than delete it altogether, maybe we could move it to the frontpage and use it as a newsfeed? (e.g. [our group webpage at Rice](solar.rice.edu)). 

This way, the first thing people see when they go to the page is what the group is and the most recent news. This could be used to advertise new projects, telecon times, meetups, etc.

**Comment by wtbarnes** [comment]
Re: the deploy preview, you can click the "Details" link on the right side of the last check labeled "Deploy preview ready!". I'll poke around a bit more to see if we can hide these other checks. I'm not sure what they are really. The "failure" is because some images are still being served over HTTP and not HTTPS.

**Comment by wtbarnes** [comment]
Re: the new default image, sure. What is the URL for that one?

**Comment by ehsteve** [comment]
@wtbarnes yeah, I like your idea of moving projects off the home page as well and using it as a news feed. Let's do that. Let's keep the current header box "Python in Heliophysics" and let's replace the text that is currently "A general list of software packages for Heliophysics." with "A website to promote and facilitate the use and development of Python for Heliophysics." Add the about text to below that in it's own div and remove the about page completely then.

**Comment by wtbarnes** [comment]
OK this PR now addresses #20 as well by moving the projects and people to separate pages and placing the "About" and blogroll on the front page. The idea going forward is that the blogroll will be used as a sort of news feed for the group.

**Comment by wtbarnes** [comment]
OK if @alex-aquila is ok with these changes then I'll go ahead and merge it.

**Pull request merged**
