### PR TITLE
Add PyGS package

### PR DESCRIPTION
**Pull request by PyGSDR**
Hi there, 

This is Yu Chen, and I can be reached at yc0020@uah.edu. I just added PyGS package to this projects.yml and would like to publish our package to PyHC. Please let me know if there is anything I need to add.

### CODE REVIEW

**Comment by PyGSDR** [comment]
Hi Shawn @sapols , I was wondering if this packing is under review now?

**Comment by sapols** [comment]
Hi Yu Chen @PyGSDR, sorry for taking so long to reply. You opened this PR right before I went on vacation for 4th of July and I'm just now getting back to work. Bad timing. I have not reviewed this yet, but it will get done in the next week or two.

**Comment by sapols** [comment]
Okay, I finished my review. I've downgraded the status of "community" from "Good" to "Partially met" because your repo is missing contribution guidelines and a code of conduct (points 13 & 15 referenced in the [Review Guidelines](https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/main/_pyhc_projects/pyhc_project_grading_guidelines.md)). This is fine for now; I'll go ahead and merge this PR, which will officially add PyGS to PyHC. Congrats and welcome! 

After you get around to adding contribution guidelines and a code of conduct, feel free to open another PR to upgrade your "community" status back to "Good".

**Review by sapols — APPROVED** [review]

**Comment by PyGSDR** [comment]
> Okay, I finished my review. I've downgraded the status of "community" from "Good" to "Partially met" because your repo is missing contribution guidelines and a code of conduct (points 13 & 15 referenced in the [Review Guidelines](https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/main/_pyhc_projects/pyhc_project_grading_guidelines.md)). This is fine for now; I'll go ahead and merge this PR, which will officially add PyGS to PyHC. Congrats and welcome!
> 
> After you get around to adding contribution guidelines and a code of conduct, feel free to open another PR to upgrade your "community" status back to "Good".

**Comment by PyGSDR** [comment]
Sorry I accidentally closed this one. Hopefully it doesn't affect the progress.
Thank you so much and we will check those guidelines. @sapols

**Pull request merged**
