### PR TITLE
Displaying approved PHEPs; include PHEP-1

### PR DESCRIPTION
**Pull request by jtniehof**
This is a terrible first shot at displaying approved pheps, by someone who really doesn't understand Jekyll :) but hopefully it can get the idea across. It's sort of the complement to heliophysicsPy/standards#26 ...that has a Python snippet which extracts the necessary yaml, and this then just dumps the YAML, more-or-less. Untested.

Maybe we should have the DOI in there somewhere, too.

### CODE REVIEW

**Comment by sapols** [comment]
Apparently the liquid conditional logic isn't gonna let us do that `or`, so my latest commit, while uglier in code, is needed to fix the display. With that fix the page now displays like:
Screen Shot 2024-04-16 at 4 40 44 PM

Calling that a stopping point. I'll continue working on this in the morning.

**Comment by jtniehof** [comment]
That's probably actually more clear. Thanks for getting that working. I'll poke around and see what I can do about including DOI.

**Comment by jtniehof** [comment]
I just pushed an update to heliophysicsPy/standards#26 that inserts the DOI into the YAML, so we will want an additional column. I'm thinking at the very end (after revision) and then:
```
          <td>
            <a href="https://doi.org/{{ phep.DOI }}">doi:{{ phep.DOI }}</a>
          </td>
```

**Comment by sapols** [comment]
I'll note that for the DOI to display properly in the table, the `DOI` entry in the yaml should look like `10.5281/zenodo.10988007` (e.g. don't include `http://` in that entry).

**Comment by jtniehof** [comment]
Just to note, once heliophysicsPy/standards#22 is merged and the release cut, I will finish the Zenodo upload and mark this ready to merge.

**Comment by jtniehof** [comment]
Zenodo is uploaded, so @sapols , ready to merge!

**Review by sapols — APPROVED** [review]

**Pull request merged**
