### PR TITLE
Add a recording alert to the Spring 2021 Meeting page

### PR DESCRIPTION
**Pull request by sapols**
Just giving our members some heads up that we'll be recording the Zoom sessions.

I waffled between just italics and bold+italics but landed on just italics because both looked a little overdramatic. I also considered putting it after the following sentence, but I liked the colon leading right into the dates/times. Then I considered putting it below them but thought it was too far down the page.🤷‍♂️

Open to suggestions.

### CODE REVIEW

**Comment by sapols** [comment]
Should I say this in the blog post about the meeting too?

**Review by jibarnum — CHANGES_REQUESTED** [review]
I agree, bolded *and* italicized would've been overkill. Looks good as is, where it is. Probably a good idea to also add this to the blog post, as you suggested. Hence, requesting changes.

**Comment by sapols** [comment]
@jibarnum done.

**Comment by jibarnum** [comment]
LGTM! 👍

**Pull request merged**
