### PR TITLE
Add XRTpy as a PyHC project

### PR DESCRIPTION
**Pull request by namurphy**
This PR is to add [XRTpy](https://xrtpy.readthedocs.io/en/latest/) ([repo](https://github.com/HinodeXRT/xrtpy)) as a PyHC project.  It also adds `"hinode"` to the taxonomy.

This PR is of interest to @joyvelasquez & @jslavin.

### CODE REVIEW

**Review by sapols — APPROVED** [review]

**Comment by jibarnum** [comment]
@namurphy can we mark this as "ready for review"? I'd love to get XRTpy involved with the PyHC community (and get them on a telecon!).

**Comment by namurphy** [comment]
@joyvelasquez — does the information about XRTpy in this PR look good to you?

**Comment by joyvelasquez** [comment]
Yes!
Looks great, thanks Nick!

**Comment by namurphy** [comment]
Thank you for the reviews, and happy to have XRTpy officially join!

**Pull request merged**
