### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by nabobalis**
Overall probably a very pointless PR but I couldn't help myself.

The main changes:
1. Setting the homepage to say PyHC instead of just home on the tab title.
2. Two typos
3. Some incorrect unicode characters 

Everything else is just whitespace changes either to attempt to make it look prettier, or to try and follow the markdown spec in places.

I rendered it locally, I had to add a new bundle for it work, I could not spot anything I had broken on the surface.

### CODE REVIEW

**Comment by sapols** [comment]
Thanks for the PR but it’s hard to tell where the important changes are. It looks like your IDE did a bunch of auto-formatting that we didn’t ask for (changing indents from 4 spaces to 2, etc.). Will you please revert all the formatting changes and keep just your three main changes?

**Comment by nabobalis** [comment]
> Thanks for the PR but it’s hard to tell where the important changes are. It looks like your IDE did a bunch of auto-formatting that we didn’t ask for (changing indents from 4 spaces to 2, etc.). Will you please revert all the formatting changes and keep just your three main changes?

All of those changes I did deliberately to ensure a consistently across the files and to fix a bunch of formatting issues.

If you don't want them I can remove them.

**Comment by nabobalis** [comment]
I have undone all the extra whitespace/indentation changes.

**Comment by sapols** [comment]
Well I certainly do appreciate you taking such a close eye through our code base! Sorry I assumed that was IDE auto-formatting and not your manual labor. But this is much easier for me to review now that it's not 62 changed files. 

I'm happy with these improvements except for where you changed dashes to hyphens; we were intentionally using en dashes because it's the correct punctuation mark for intervals. So please revert those hyphens back to dashes then I'll gladly merge. Thanks.

**Comment by nabobalis** [comment]
> I'm happy with these improvements except for where you changed dashes to hyphens; we were intentionally using en dashes and em dashes for intervals and for separating clauses, respectively, because they're the correct punctuation marks. It would be incorrect to use hyphens in those contexts. So please revert those hyphens back to dashes then I'll gladly merge. Thanks.

I have fixed my mistakes regarding this matter.

**Review by sapols — APPROVED** [review]

**Pull request merged**
